# api_platform:
#     title: Hello API Platform
#     version: 1.0.0
#     defaults:
#         stateless: true
#         cache_headers:
#             vary: ['Content-Type', 'Authorization', 'Origin']
            
api_platform:
    title: 'API Platform'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
